import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="max-w-md mx-auto rounded-xl shadow-md overflow-hidden md:max-w-4xl">
          <div className="text-4xl text-red-500 text-center">Next Garou</div>
        </header>
        <main className="max-w-md mx-auto rounded-xl shadow-md overflow-hidden md:max-w-4xl">{children}</main>
      </body>
    </html>
  );
}
